# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[(b'espresso', b'Espresso'), (b'americano', b'Americano'), (b'latte', b'latte')], max_length=15)),
                ('beans', models.CharField(max_length=15)),
                ('contains_milk', models.BooleanField(default=False)),
                ('time_preparing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.CoffeeSize'),
        ),
    ]
