# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee_type', models.CharField(choices=[(b'espresso', b'Espresso'), (b'americano', b'Americano'), (b'latte', b'Latte')], max_length=15)),
                ('beans', models.CharField(max_length=15)),
                ('coffee_quantity', models.IntegerField()),
                ('size', models.IntegerField(choices=[(120, b'Normal'), (240, b'Large')])),
                ('extra_quantity', models.IntegerField(blank=True, null=True)),
                ('contains_milk', models.BooleanField(default=False)),
                ('time_preparing', models.IntegerField()),
            ],
        ),
    ]
